### ISSUE TITLE
New Nightly feature removes jemalloc, resulting in potentially smaller binaries

### ISSUE THREAD

**Issue by SpireFlux** [JElchison/small-portable-rust-cargo#1]
https://www.reddit.com/r/rust/comments/9twam5/jemalloc_was_just_removed_from_the_standard/

> A stripped hello world with stable rust is 414.5KiB large
> The nightly that just landed produces a stripped hello world of 194.3KiB
> We got 220.2 KiB less on stripped hello world.
> Non-stripped stable rust hello-world is about 3.8 MiB
> Non-stripped nightly rust hello-world is about 2.3 MiB
> NOTE: in release mode

**Comment by JElchison** [comment]
Updated benchmarks.  Thanks, @SpireFlux!
